name: V2Ray Collector

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # دانلود و آماده‌سازی هسته Xray
      - name: Setup Xray Core
        run: |
          wget -q https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip -q Xray-linux-64.zip xray
          chmod +x xray
          rm Xray-linux-64.zip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run collector script
        env:
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
        run: python collector.py 

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sub.txt sub_raw.txt
          
          if git diff --staged --quiet; then
            echo "⚠️ هیچ تغییر یا سرور زنده‌ای یافت نشد، کامیت انجام نمی‌شود."
          else
            git commit -m "🚀 Update Configs: $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
